### ISSUE TITLE
Automated Heroku deployments pushed from passing Travis CI builds

### ISSUE THREAD

**Issue by travisjwarren** [teamtemp/teamtemp#23]
Using TravisCI, config file can be modified to push a deployment to Heroku.

Example can be seen in my [Team Temp](https://github.com/travisjwarren/train_track/blob/master/.travis.yml)

**Comment by willthames** [comment]
What process says 'this code has been reviewed' prior to the deploy? Is it the acceptance of the PR?

That seems acceptable to me, although we still need to work out what we're going to do with original teamtemp.

**Comment by travisjwarren** [comment]
Yes @willthames, acceptance of the pull request would indicate to me that the code is deployable.  If it is not, do not accept the pull request.

**Comment by willthames** [comment]
Ok, sounds good to me, and agree that we wouldn't need to change branching model for this to work.

**Comment by travisjwarren** [comment]
@willthames "still need to work out what we're going to do with original teamtemp."  Not sure I follow on this?

**Comment by willthames** [comment]
What is currently teamtemp.herokuapp.com is not what is master branch on github. So automating heroku deployments not a big win if we haven't worked out what to do with existing heroku deployment! We have no non-breaking upgrade path.

**Comment by travisjwarren** [comment]
Ah, so the master branch is not currently deployed at all?

The long term plan was to move functionality from the current deployment into the master repository.  We should be able to migrate Andrew's data into our new deployment as part of that process.

If we want a 'staging' environment for our current master, I am happy to create a new Herouku app and set up an automated deploy to it.

**Comment by travisjwarren** [comment]
```
language: python
install:
- pip install -r requirements.txt
- pip install coveralls
script: coverage run manage.py test
after_success: coveralls
deploy:
  provider: heroku
  api_key:
    secure: GENERATE_KEY
  app: real-team-temp
  on:
    repo: teamtemp/teamtemp
  run:
    python manage.py migrate --noinput
    python manage.py collectstatic --noinput
```
